config/routes.rb
Rails.application.routes.draw do

  get "up" => "rails/health#show", as: :rails_health_check

  # get "lists", to: "lists#index"
  # get "lists/:id", to: "lists#show", as: :list
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :list_id, uniqueness: { scope: :movie_id, message: "Bookmark already exists for this list and movie combination" }
  validates :comment, presence: true, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many  :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence:true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence:true, uniqueness: true
  validates :overview, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @movies = Movie.all

  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @movies = @list.movies
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container mb-3">
  <h1>Add a new bookmark</h1>
  <div class="row justify-content-center">
    <%= simple_form_for [@movie, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.input :movie, collection: Movie.all, input_html: {multiple: true}, include_hidden: false %>
    <%= f.submit "Add a new list", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container mb-3">
 <div class="row justify-content-center">
    <h1>Lists</h1>
    <p>
      <% @lists.each do |list| %>
        <%= link_to list.name, list_path(list) %>
      <% end %>
    </p>

    <%= link_to "Add a new list", new_list_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container mb-3">
  <h1>Add a new list</h1>
  <div class="row justify-content-center">
    <%= simple_form_for [@list] do |f| %>
    <%= f.input :name %>
    <%= f.submit "Add a new list", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<ul>
  <% @movies.each do |movie| %>
    <li>
      <%= movie.title %>
      <%= movie.overview %>
      <%= movie.rating %>
    </li>
  <% end %>
</ul>

<%= link_to "Add a new film", new_list_bookmark_path(@list), class: "btn btn-primary" %>